-- INSERTAR CLAVES DE UNIDAD (Las más comunes)
INSERT INTO "SatClaveUnidad" (id, clave, nombre, "createdAt", activo) VALUES 
(gen_random_uuid(), 'H87', 'Pieza', NOW(), true),
(gen_random_uuid(), 'E48', 'Unidad de servicio', NOW(), true),
(gen_random_uuid(), 'EA', 'Elemento', NOW(), true),
(gen_random_uuid(), 'KGM', 'Kilogramo', NOW(), true),
(gen_random_uuid(), 'LTR', 'Litro', NOW(), true),
(gen_random_uuid(), 'MTR', 'Metro', NOW(), true),
(gen_random_uuid(), 'MTK', 'Metro cuadrado', NOW(), true),
(gen_random_uuid(), 'MTQ', 'Metro cúbico', NOW(), true),
(gen_random_uuid(), 'XBX', 'Caja', NOW(), true),
(gen_random_uuid(), 'XPK', 'Paquete', NOW(), true),
(gen_random_uuid(), 'HUR', 'Hora', NOW(), true),
(gen_random_uuid(), 'DAY', 'Día', NOW(), true),
(gen_random_uuid(), 'MON', 'Mes', NOW(), true),
(gen_random_uuid(), 'ACT', 'Actividad', NOW(), true),
(gen_random_uuid(), 'ROM', 'Habitación', NOW(), true),
(gen_random_uuid(), 'ZZ', 'Mutuamente definido', NOW(), true),
(gen_random_uuid(), 'KWH', 'Kilovatio hora', NOW(), true),
(gen_random_uuid(), 'FOT', 'Pie', NOW(), true),
(gen_random_uuid(), 'GLI', 'Galón', NOW(), true),
(gen_random_uuid(), 'C62', 'Pieza (uno)', NOW(), true),
(gen_random_uuid(), 'PR', 'Par', NOW(), true),
(gen_random_uuid(), 'SET', 'Conjunto', NOW(), true),
(gen_random_uuid(), 'TNE', 'Tonelada métrica', NOW(), true),
(gen_random_uuid(), 'GRM', 'Gramo', NOW(), true),
(gen_random_uuid(), 'CMT', 'Centímetro', NOW(), true)
ON CONFLICT (clave) DO NOTHING;

-- INSERTAR CLAVES DE PRODUCTOS/SERVICIOS (Tecnología, Servicios, Comercio)
INSERT INTO "SatClaveProdServ" (id, clave, descripcion, "createdAt", activo) VALUES 
-- Tecnología / TI (Tu área)
(gen_random_uuid(), '43202000', 'Dispositivos de almacenamiento', NOW(), true),
(gen_random_uuid(), '43202009', 'Discos duros', NOW(), true),
(gen_random_uuid(), '43211500', 'Computadores', NOW(), true),
(gen_random_uuid(), '43211507', 'Computadores de escritorio', NOW(), true),
(gen_random_uuid(), '43211503', 'Computadores portátiles (Notebooks)', NOW(), true),
(gen_random_uuid(), '43211900', 'Monitores', NOW(), true),
(gen_random_uuid(), '43212100', 'Impresoras informáticas', NOW(), true),
(gen_random_uuid(), '43222600', 'Equipo de red', NOW(), true),
(gen_random_uuid(), '43222609', 'Enrutadores (Routers)', NOW(), true),
(gen_random_uuid(), '43222612', 'Conmutadores de red (Switches)', NOW(), true),
(gen_random_uuid(), '43232800', 'Software de red o servidor', NOW(), true),
(gen_random_uuid(), '43232900', 'Software de utilidades', NOW(), true),
(gen_random_uuid(), '81111500', 'Servicios de consultoría de TI', NOW(), true),
(gen_random_uuid(), '81111504', 'Servicios de integración de sistemas de TI', NOW(), true),
(gen_random_uuid(), '81111507', 'Servicios de desarrollo de software', NOW(), true),
(gen_random_uuid(), '81111800', 'Servicios de infraestructura de TI', NOW(), true),
(gen_random_uuid(), '81111801', 'Servicios de mantenimiento y soporte de TI', NOW(), true),
(gen_random_uuid(), '81111805', 'Servicios de alojamiento de datos (Hosting)', NOW(), true),
(gen_random_uuid(), '81112200', 'Servicios de mantenimiento de software', NOW(), true),

-- Servicios Generales Profesionales
(gen_random_uuid(), '80101500', 'Servicios de consultoría de negocios', NOW(), true),
(gen_random_uuid(), '84111500', 'Servicios contables', NOW(), true),
(gen_random_uuid(), '84111506', 'Servicios de facturación', NOW(), true),
(gen_random_uuid(), '80121600', 'Servicios de asesoría legal', NOW(), true),
(gen_random_uuid(), '80111600', 'Servicios de recursos humanos', NOW(), true),
(gen_random_uuid(), '82101500', 'Publicidad impresa', NOW(), true),
(gen_random_uuid(), '82101600', 'Publicidad en internet', NOW(), true),
(gen_random_uuid(), '82101603', 'Servicios de marketing en redes sociales', NOW(), true),

-- Comercio y Otros
(gen_random_uuid(), '01010101', 'No existe en el catálogo', NOW(), true),
(gen_random_uuid(), '50202200', 'Bebidas no alcohólicas', NOW(), true),
(gen_random_uuid(), '50202300', 'Bebidas no alcohólicas (Agua)', NOW(), true),
(gen_random_uuid(), '50192700', 'Platos preparados', NOW(), true),
(gen_random_uuid(), '90101500', 'Establecimientos para comer y beber', NOW(), true),
(gen_random_uuid(), '90101501', 'Restaurantes', NOW(), true),
(gen_random_uuid(), '90101503', 'Establecimientos de comida rápida', NOW(), true),
(gen_random_uuid(), '78111800', 'Servicios de transporte de pasajeros', NOW(), true),
(gen_random_uuid(), '78111802', 'Servicios de taxis', NOW(), true),
(gen_random_uuid(), '78101800', 'Transporte de carga por carretera', NOW(), true),
(gen_random_uuid(), '78102200', 'Servicios postales y de mensajería', NOW(), true),
(gen_random_uuid(), '72101500', 'Servicios de apoyo a la construcción', NOW(), true),
(gen_random_uuid(), '72101508', 'Mantenimiento de edificios', NOW(), true),
(gen_random_uuid(), '76111500', 'Servicios de limpieza', NOW(), true),
(gen_random_uuid(), '25172500', 'Neumáticos', NOW(), true),
(gen_random_uuid(), '25191500', 'Baterías', NOW(), true),
(gen_random_uuid(), '15101500', 'Combustibles líquidos (Gasolina)', NOW(), true),
(gen_random_uuid(), '15101506', 'Gasolina regular', NOW(), true),
(gen_random_uuid(), '15101505', 'Gasolina premium', NOW(), true),
(gen_random_uuid(), '31162800', 'Tornillos y sujetadores', NOW(), true),
(gen_random_uuid(), '31201500', 'Cinta adhesiva', NOW(), true),
(gen_random_uuid(), '44121700', 'Suministros de escritura (Bolígrafos)', NOW(), true),
(gen_random_uuid(), '14111500', 'Papel de impresión', NOW(), true),
(gen_random_uuid(), '80141600', 'Actividades de ventas y promoción', NOW(), true)
ON CONFLICT (clave) DO NOTHING;
